name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make clean
      run: make clean
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install libcurl
      run: sudo apt-get install libcurl4-openssl-dev
    - name: Install libjson-c
      run: sudo apt-get install libjson-c-dev
    - name: Install libbsd-dev
      run: sudo apt-get install libbsd-dev
    - name: cmake
      run: cmake CMakeLists.txt
    - name: make all
      run: make all
